sudo: False
language: python
matrix:
  include:
    - python: 3.6
    - python: 3.5
    - python: 3.4
    - python: 3.3
    - python: 2.7
    - python: 2.6
install:
install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-env python=$TRAVIS_PYTHON_VERSION pytest pandas
  - source activate test-env
  - pip install -e .
script:
  - make
notifications:
  email: false
